### PR TITLE
Remove outdated ipyscales dependency.

### PR DESCRIPTION
**Pull request by jasongrout**
See https://github.com/vidartf/ipydatawidgets/pull/22 where the dependency was moved from the pip package.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Review by vidartf — APPROVED** [review]

**Comment by jasongrout** [comment]
@vidartf - can you merge this? I won't be able to merge until after this is merged, adding me to the maintainers.

**Comment by vidartf** [comment]
I just saw you left an open checkmark in your OP, so I wasn't sure if it was ready or not 😄 merging..

**Comment by jasongrout** [comment]
Ah, no problem. The CI does say it packaged license files: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=177301&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=430

**Pull request merged**
